disabled_rules:
    - trailing_whitespace
    #To avoid warnings using "i, c" as counters or iterators
    - variable_name_min_length
    #Shouldn't be excluded, max = 5
    - type_name
    
opt_in_rules:
    - empty_count
    - empty_string

included:
    - MVVMExample

excluded:
    - 'Carthage'
    - 'Pods'

line_length:
    warning: 120
    error: 1000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 40
    error: 100

function_parameter_count:
    warning: 5
    error: 10

type_body_length:
    warning: 40
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 16
    error: 40
    
large_tuple:
    warning: 5
    error: 10
    
identifier_name:
    allowed_symbols: "_"
    max_length:
        warning: 60
        error: 60
    min_length:
        warning: 1

reporter: "xcode"
