platform :ios, '9.0'

target 'MVVMExample' do
    use_frameworks!

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SwiftLint'

    target 'MVVMExampleTests' do
        #Add pod here if you want the access of pod in Tests target.
        #Example: pod 'RxSwift'
    end

    target 'MVVMExampleUITests' do
        #Add pod here if you want the access of pod in Tests target.
        #Example: pod 'RxSwift'
    end

end