# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMExample

  target 'MVVMExampleTests' do
    pod 'RxSwift'
    pod 'RxCocoa'
  end

  target 'MVVMExampleUITests' do
    # Pods for testing
  end

end
